name: key_bank_flutter
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10+1
  dartz: ^0.10.1
  dio: ^5.5.0+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  get_it: ^7.7.0
  flutter_bloc: ^8.1.6
  oktoast: ^3.4.0
  flutter_screenutil: ^5.9.3
  cached_network_image: ^3.3.1
  logger: ^2.4.0
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3
  go_router: ^14.2.1
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.4.1
  carousel_slider: ^4.0.0
  google_fonts: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  lint: ^2.3.0
  bloc_test: ^9.1.7
  build_runner: ^2.4.9
  http_mock_adapter: ^0.6.1
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  hive_generator: ^2.0.1
  

dependency_overrides:
  meta: ^1.15.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/

fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 100
        - asset: assets/fonts/Poppins-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900